apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubelab-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
      - env: staging
      - env: production
  template:
    metadata:
      name: kubelab-app-{{env}}
    spec:
      project: default
      source:
        repoURL: https://github.com/Justappl/kubelab-incluster
        targetRevision: HEAD
        path: apps/kubelab-app
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true